package main

const (
	SOCK_DIAG_BY_FAMILY = 20

	SizeOfUnixDiagMsg = 16
	SizeOfInetDiagMsg = 72
)

const (
	SK_MEMINFO_RMEM_ALLOC = iota
	SK_MEMINFO_RCVBUF
	SK_MEMINFO_WMEM_ALLOC
	SK_MEMINFO_SNDBUF
	SK_MEMINFO_FWD_ALLOC
	SK_MEMINFO_WMEM_QUEUED
	SK_MEMINFO_OPTMEM
	SK_MEMINFO_BACKLOG
	SK_MEMINFO_DROPS
	SK_MEMINFO_VARS
)
